import { ValuedItem } from "../../types/item";

export const MOCK_VALUED_ITEMS: ValuedItem[] = [
  {
    item: {
      id: "mock-item-1",
      name: "Mageblood",
      typeLine: "Heavy Belt",
      baseType: "Heavy Belt",
      rarity: "unique",
      category: "equipment",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQmVsdHMvTWFnZWJsb29kIiwidyI6MiwiaCI6MSwic2NhbGUiOjF9XQ/05f2fa73e6/Mageblood.png",
      itemLevel: 86,
      identified: true,
      corrupted: false,
    },
    unitPrice: 180.0,
    totalPrice: 180.0,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
  {
    item: {
      id: "mock-item-2",
      name: "Headhunter",
      typeLine: "Leather Belt",
      baseType: "Leather Belt",
      rarity: "unique",
      category: "equipment",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQmVsdHMvTGVhdGhlckJlbHQiLCJ3IjoyLCJoIjoxLCJzY2FsZSI6MX1d/505307b22f/LeatherBelt.png",
      itemLevel: 85,
      identified: true,
      corrupted: false,
    },
    unitPrice: 75.0,
    totalPrice: 75.0,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
  {
    item: {
      id: "mock-item-3",
      name: "Nimis",
      typeLine: "Topaz Ring",
      baseType: "Topaz Ring",
      rarity: "unique",
      category: "equipment",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvUmluZ3MvTmltaXMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/95aa42bc56/Nimis.png",
      itemLevel: 84,
      identified: true,
      corrupted: false,
    },
    unitPrice: 50.0,
    totalPrice: 50.0,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
  {
    item: {
      id: "mock-item-4",
      name: "The Apothecary",
      typeLine: "Divination Card",
      baseType: "Divination Card",
      rarity: "divination",
      category: "card",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvRGl2aW5hdGlvbi9JbnZlbnRvcnlJY29uIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/f34bf8c10b/InventoryIcon.png",
      stackSize: 1,
      maxStackSize: 5,
      identified: true,
    },
    unitPrice: 35.0,
    totalPrice: 35.0,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
  {
    item: {
      id: "mock-item-5",
      name: "Mirror Shard",
      typeLine: "Currency",
      baseType: "Mirror Shard",
      rarity: "currency",
      category: "currency",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lEdXBsaWNhdGVTaGFyZCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/14f6b3b55d/CurrencyDuplicateShard.png",
      stackSize: 1,
      maxStackSize: 20,
      identified: true,
    },
    unitPrice: 22.0,
    totalPrice: 22.0,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
  {
    item: {
      id: "mock-item-6",
      name: "Awakened Enlighten Support",
      typeLine: "Support Gem",
      baseType: "Support Gem",
      rarity: "gem",
      category: "gem",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L0VubGlnaHRlbiIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/72b896b026/Enlighten.png",
      itemLevel: 5,
      identified: true,
      corrupted: true,
    },
    unitPrice: 18.0,
    totalPrice: 18.0,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
  {
    item: {
      id: "mock-item-7",
      name: "Divine Orb",
      typeLine: "Currency",
      baseType: "Divine Orb",
      rarity: "currency",
      category: "currency",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lNb2RWYWx1ZXMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/e1a54ff97d/CurrencyModValues.png",
      stackSize: 5,
      maxStackSize: 20,
      identified: true,
    },
    unitPrice: 1.0,
    totalPrice: 5.0,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
  {
    item: {
      id: "mock-item-8",
      name: "Chaos Orb",
      typeLine: "Currency",
      baseType: "Chaos Orb",
      rarity: "currency",
      category: "currency",
      icon: "https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQ3VycmVuY3lSZXJvbGxSYXJlIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/c201525a17/CurrencyRerollRare.png",
      stackSize: 240,
      maxStackSize: 20,
      identified: true,
    },
    unitPrice: 0.0067,
    totalPrice: 1.6,
    currency: "divine",
    priceSource: "poe.ninja",
    priceAvailable: true,
    lastUpdated: Date.now(),
  },
];
